### ISSUE TITLE
Do you support ESP32S2？

### ISSUE THREAD

**Issue by afterow** [polhenarejos/pico-fido#100]
Hello, does this project support ESP32S2

**Comment by polhenarejos** [comment]
Not at this moment.

**Comment by afterow** [comment]
I flashed the Pico Fido with version 6.4, but it doesn't work properly, keeps plugging and ejecting

![Image](https://github.com/user-attachments/assets/81ba6229-e211-43b5-938a-e9647e6e0629)

**Comment by polhenarejos** [comment]
It crashes on boot.

Which model of S2 do you use?

**Comment by afterow** [comment]
My equipment is esp32-s2 mini
```
C:\Users\afterow\Desktop\esptool-s3>esptool --chip esp32s2 --port COM3 read_mac
esptool.py v4.8.1
Serial port COM3
Connecting.....
Chip is ESP32-S2FNR2 (revision v1.0)
Features: WiFi, Embedded Flash 4MB, Embedded PSRAM 2MB, ADC and temperature sensor calibration in BLK2 of efuse V2
Crystal is 40MHz
MAC: d8:3b:da:c9:7c:e8
Uploading stub...
Running stub...
Stub running...
MAC: d8:3b:da:c9:7c:e8
Error: ESP32-S2FNR2 (revision v1.0) chip was placed into download mode using GPIO0.
esptool.py can not exit the download mode over USB. To run the app, reset the chip manually.
To suppress this note, set --after option to 'no_res
```

**Comment by polhenarejos** [comment]
Do you have the chance to debug on UART0?

**Comment by afterow** [comment]
I don't know what UART0 is, but I can help you, for example through remote desktop

**Comment by polhenarejos** [comment]
It is the serial port for debugging. It requires an additional hardware like a USB-to-TTL.

**Comment by afterow** [comment]
I have a CH340B, I wonder if it can be used.

**Comment by polhenarejos** [comment]
Not sure how it works but if you know how to open a serial port it might work. Look for uart0 tx and rx pins in the datasheet of your board and probe them with your ch340b.

**Comment by emf37** [comment]
> Not sure how it works but if you know how to open a serial port it might work. Look for uart0 tx and rx pins in the datasheet of your board and probe them with your ch340b.

hello, I have same issue. the Pico-FIDO with ESP32-S2FH4 just keeps plugging and ejecting on windows 10. 
Here is a log file exported from the console on "www.picokeys.com/esp32-flasher",also I flashed by this.
Hope this helps. 
Thank you.
 
[esp-web-tools-logs.txt](https://github.com/user-attachments/files/19123057/esp-web-tools-logs.txt)

**Comment by polhenarejos** [comment]
Thanks, very useful log. I see the problem: ESP32-S2 is single core and Pico Fido is designed to work with two cores at least. I was not aware of it. I'll try to leverage FreeRTOS for core management but I do not have an ESP32-S2 to test it.

Do you have skills for building ESP32-S2 images?

**Comment by afterow** [comment]
I will compile it myself



---- Replied Message ----
| From | Pol ***@***.***> |
| Date | 03/07/2025 16:41 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [polhenarejos/pico-fido] Do you support ESP32S2？ (Issue #100) |

Thanks, very useful log. I see the problem: ESP32-S2 is single core and Pico Fido is designed to work with two cores at least. I was not aware of it. I'll try to leverage FreeRTOS for core management but I do not have an ESP32-S2 to test it.

Do you have skills for building ESP32-S2 images?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>

polhenarejos left a comment (polhenarejos/pico-fido#100)

Thanks, very useful log. I see the problem: ESP32-S2 is single core and Pico Fido is designed to work with two cores at least. I was not aware of it. I'll try to leverage FreeRTOS for core management but I do not have an ESP32-S2 to test it.

Do you have skills for building ESP32-S2 images?

**Comment by afterow** [comment]
I will compile it myself

**Comment by polhenarejos** [comment]
I pushed a fix for esp32-s2 in the development branch. You can build yourself or wait until tomorrow for the nightly development build.

**Comment by 79812b** [comment]
> I pushed a fix for esp32-s2 in the development branch. You can build yourself or wait until tomorrow for the nightly development build.

btw will this work for esp32 c3 speed xiao

**Comment by polhenarejos** [comment]
No, C3 does not have USB OTG stack.

**Comment by afterow** [comment]
> No, C3 does not have USB OTG stack.

I tested the latest development version on the ESP32-S2 today, and the issue remains unresolved. I have decided to give up on using this device since the price of the ESP32-S3 is currently the same as that of the ESP32-S2 here in China. 

Fortunately, the project [esp32_u2f](https://github.com/jocover/esp32_u2f) can be used on the ESP32-S2.
