### ISSUE TITLE
🐛 WebAuthn Authentication Fails After Device Removal on pico-fido

### ISSUE THREAD

**Issue by afterow** [polhenarejos/pico-fido#110]
### Description
After flashing pico-fido, the first WebAuthn authentication succeeds, but authentication fails after removing the device. Testing revealed that re-setting the PIN using Windows Hello miraculously restored WebAuthn authentication to normal.

### Environment
- Operating System: Windows 11
- Firmware Version: esp32-s3_6.2
- Browser: Chrome 133.0.6943.60
- Chip Model: ESP32-S3 (QFN56)

### Steps to Reproduce
1. Flash pico-fido
2. Bind the security key
3. Remove the device
4. WebAuthn authentication

### Expected Behavior
Successful WebAuthn authentication.

### Actual Behavior
Login fails.

<img src="https://github.com/user-attachments/assets/69033266-b276-4d85-b002-05554645f063" alt="Error Screenshot" width="341" />

**Comment by polhenarejos** [comment]
Can you flash the nightly development build?

**Comment by afterow** [comment]
I also flashed the nightly development build version, but the effect is the same.

**Comment by afterow** [comment]
#91 I think my situation is the same as his

I believe this commit is the cause: [commit 6a67800](https://github.com/polhenarejos/pico-fido/commit/6a678000570ccf95dbc67446a0fe4fdddfc5f28e).

**Comment by polhenarejos** [comment]
But it is solved in the last development commit. Did you enrolled again the key after the development flash?

**Comment by afterow** [comment]
> But it is solved in the last development commit. Did you enrolled again the key after the development flash?

Could you release a 6.2rc version? Your regular release versions do not have firmware for ESP32. I have tested nightly builds and other versions, but they do not work.

**Comment by polhenarejos** [comment]
It’d the same as nightly builds. 

This the last https://github.com/polhenarejos/pico-fido/releases/download/nightly-development/pico_fido_esp32-s3.bin

Be sure you register again the key in Windows hello. It will not work with the previous one.

**Comment by afterow** [comment]
I flashed the version you sent and it's still the same after unplugging it

![Image](https://github.com/user-attachments/assets/26851adf-74a4-424b-9252-5c216e9e4d69)

**Comment by polhenarejos** [comment]
I don't understand clearly the problem. Are you trying to register and login to Github or Windows?
Your key is PIN protected. So, it is normal that if you don't introduce the PIN it will not work. From the GIF you upload, I don't see Github asking you for a PIN.

**Comment by lifetyper** [comment]
I thinks this commit https://github.com/polhenarejos/pico-fido/commit/bdbdd92be8783d85aa12832b56f005dc1832c976 fixed this issue,take a try.

**Comment by afterow** [comment]
This issue has been fixed in commit [bdbdd92](https://github.com/polhenarejos/pico-fido/commit/bdbdd92be8783d85aa12832b56f005dc1832c976)
